-- MySQL Script generated by MySQL Workbench
-- sáb 23 sep 2023 08:29:18
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema forochallenge
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `forochallenge` ;

-- -----------------------------------------------------
-- Schema forochallenge
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `forochallenge` ;
USE `forochallenge` ;

-- -----------------------------------------------------
-- Table `forochallenge`.`topicos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `forochallenge`.`topicos` ;

CREATE TABLE IF NOT EXISTS `forochallenge`.`topicos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(200) NOT NULL,
  `mensaje` VARCHAR(500) NOT NULL,
  `fecha_creacion` DATE NOT NULL,
  `estatus` TINYINT(1) NOT NULL,
  `autor` VARCHAR(50) NOT NULL,
  `curso` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `autor_UNIQUE` (`autor` ASC) VISIBLE,
  UNIQUE INDEX `titulo_UNIQUE` (`titulo` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `forochallenge`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `forochallenge`.`usuario` ;

CREATE TABLE IF NOT EXISTS `forochallenge`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre_usuario` VARCHAR(20) NOT NULL,
  `clave` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nombre_usuario_UNIQUE` (`nombre_usuario` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
